openAI_chatgpt:
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o-mini-2024-07-18
    file_model : text-davinci-003
    role: system
    temperature : 1.0
    max_tokens : 4000
    top_p : 1.0
    frequency_penalty : 0
    presence_penalty : 0
    cached: false
    cache_time: 3600
    cache_keyword: OpenAI_cache